// <auto-generated />
namespace _1811062025_HoMinhTrung_BigSchool.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class ByKyTa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ByKyTa));
        
        string IMigrationMetadata.Id
        {
            get { return "202106280726504_ByKyTa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
